### ISSUE TITLE
ZebraLogic LLM Requests

### ISSUE THREAD

**Issue by jd-3d** [yuchenlin/ZeroEval#1]
If you could test the following on ZebraLogic that would be great (from reddit LocalLlama community:
1) Wizard 8x22b
2) Mixtral 8x22b
3) Mixtral 8x7b
4) Command-r-plus
5) Mistral Nemo 12B
6) Llama3 405B (when it comes out)

**Comment by yuchenlin** [comment]
thank you very much! will keep adding these models gradually! `Mistral Nemo 12B` and `Command-r-plus` will be added sooner!

**Comment by AshD** [comment]
Could you test trained model and it's expanded mergekit version. _Want to see if making the same model bigger results in higher test scores?_

For example when you test Command-r-plus, could you test **nitky/Megac4ai-command-r-plus**
It is an expanded version of the same model created with mergekit.

**Comment by fairydreaming** [comment]
I think it's also a good idea to check Nemotron-4-340B. In my [farel-bench](https://github.com/fairydreaming/farel-bench/) benchmark it lost only to the updated DeepSeek-V2.

**Comment by fairydreaming** [comment]
@jd-3d @yuchenlin Info on https://platform.deepseek.com/api-docs/pricing/ says: 
> (1) The backend model of deepseek-chat and deepseek-coder has been updated to DeepSeek-V2-0628 and DeepSeek-Coder-V2-0614, you can access them without modification to the model name.

So if you ran the benchmark by using API after release of the updated DeepSeek-V2 then you used the updated model, not the original one.

**Comment by yuchenlin** [comment]
> @yuchenlin, can you clarify if the DeepSeek-V2-Chat result is the new/improved DeepSeek-V2-Chat-0628 version?

Yes, we run the deepseek models via their API (on July 4) after they switched the backend model to 0628

**Comment by yuchenlin** [comment]
> I think it's also a good idea to check Nemotron-4-340B. In my [farel-bench](https://github.com/fairydreaming/farel-bench/) benchmark it lost only to the updated DeepSeek-V2.

yeah, will do. sadly our nvidia nim api credit is used up. will probably need to register a new account :(

**Comment by Lissanro** [comment]
I see Llama 3.1 405B already got added recently, and almost at the top! It would be great to see some other open weight models in the table:

- Llama 3.1 70B Instruct (would be interesting to see how Llama 70B 3.1 compares against the original Llama 3 70B)
- Llama 3.1 8B Instruct
- Mistral Large 2

**Comment by yuchenlin** [comment]
> I see Llama 3.1 405B already got added recently, and almost at the top! It would be great to see some other open weight models in the table:
> 
> * Llama 3.1 70B Instruct (would be interesting to see how Llama 70B 3.1 compares against the original Llama 3 70B)
> * Llama 3.1 8B Instruct
> * Mistral Large 2

All models are added now!
